Ensure cleanup runs when daemonized. Add var check to shutup readlink.

diff --git a/files/default/lxc-awesome-ephemeral b/files/default/lxc-awesome-ephemeral
--- a/files/default/lxc-awesome-ephemeral
+++ b/files/default/lxc-awesome-ephemeral
@@ -48,31 +48,40 @@ DAEMON=0
 
 cleanup_dirs()
 {
+    if [ $LXC_DIR = '/' ]; then
+        echo "ABORT ABORT ABORT -> LXC Directory set to root. Will. Not. Delete!"
+        exit 42
+    fi
     # echo "umounting ephemeral_bind_dir $EPHEMERAL_BIND_DIR" >&2
-    sudo umount $EPHEMERAL_BIND_DIR
+    sudo umount $EPHEMERAL_BIND_DIR > /dev/null 2>&1
     # echo "umounting lxc_dir $LXC_DIR" >&2
-    sudo umount $LXC_DIR/rootfs
+    sudo umount $LXC_DIR/rootfs > /dev/null 2>&1
     # echo "umounting overlay" >&2
     if [ ! $HOST_OVERLAY_DIRECTORY ]; then
-        sudo umount $OVERLAY_DIR
+        sudo umount $OVERLAY_DIR > /dev/null 2>&1
     fi
     # remove all contents of the content dir
-    sudo rmdir $LXC_DIR/ephemeralbind
-    sudo rmdir $LXC_DIR/rootfs
-    sudo rm -f $LXC_DIR/*
+    sudo rm -rf $LXC_DIR
 
-    # echo "rming lxc_dir $LXC_DIR" >&2
-    sudo rmdir $LXC_DIR
     # echo "rming overlay dir $OVERLAY_DIR" >&2
     if [ $HOST_OVERLAY_DIRECTORY ]; then
+        if [ $HOST_OVERLAY_DIRECTORY = '/' ]; then
+            echo "ABORT ABORT ABORT -> Overlay Directory set to root. Will. Not. Delete!"
+            exit 42
+        fi
+
         if [ $VIRT_DIR ]; then
-            sudo umount $VIRT_MNT
-            sudo rmdir $VIRT_MNT
-            sudo rm $VIRT_DEV
+            sudo umount $VIRT_MNT > /dev/null 2>&1
+            sudo rmdir $VIRT_MNT > /dev/null 2>&1
+            sudo rm -f $VIRT_DEV
         fi
         sudo rm -rf $HOST_OVERLAY_DIRECTORY
     else
-        sudo rmdir $OVERLAY_DIR
+        if [ $OVERLAY_DIR = '/' ]; then
+            echo "ABORT ABORT ABORT -> Overlay Directory set to root. Will. Not. Delete!"
+            exit 42
+        fi
+        sudo rm -rf $OVERLAY_DIR
     fi
 }
 
@@ -280,11 +289,11 @@ setup_container()
         path=`echo -n $line | awk '{print $2}'`
         # If LXC_BIND is not set, or the mount destination of this line is not
         # LXC_BIND...
-        if [ -z "$LXC_BIND" -o "`readlink -f $path`" != "`readlink -f $LXC_DIR/rootfs$LXC_BIND`" ];
+        if [ -n "$path" ] && [ -z "$LXC_BIND" -o "`readlink -f $path`" != "`readlink -f $LXC_DIR/rootfs$LXC_BIND`" ];
             then
             # ...then we should write some form of this line.
             # If this line is a bind...
-            if [ `echo -n $line | awk '{print $4}'` == "bind" ]; then
+            if [ `echo -n $line | awk '{print $4}'` = "bind" ]; then
                 # ...we should rewrite it as an overlay.
                 source=`echo -n $line | awk '{print $1}'`
                 upperdir=$EPHEMERAL_BIND_DIR$source
@@ -442,6 +451,9 @@ handle_container()
     start_container
     RET=$?
     stop_container
+    if [ $DAEMON -eq 1 ]; then
+      cleanup
+    fi
     exit $RET
 }
 
